export default [
  {"id":"Bahasa Indonesia"},
  {"ms":"Bahasa Melayu"},
  {"ca":"Català"},
  {"da":"Dansk"},
  {"de":"Deutsch"},
  {"en":"English"},
  {"es":"Español"},
  {"el":"Eλληνικά"},
  {"fr":"Français"},
  {"it":"Italiano"},
  {"hu":"Magyar"},
  {"nl":"Nederlands"},
  {"no":"Norsk"},
  {"pl":"Polski"},
  {"pt":"Português"},
  {"fi":"Suomi"},
  {"sv":"Svenska"},
  {"tr":"Türkçe"},
  {"is":"Íslenska"},
  {"cs":"Čeština"},
  {"ru":"Русский"},
  {"th":"ภาษาไทย"},
  {"zh":"中文 (简体)"},
  {"zh-TW":"中文 (繁體)"},
  {"ja":"日本語"},
  {"ko":"한국어"}
];
